name: CMake Build

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build-ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: 2.1. Obtaining OpenSees Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Restore conan cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.conan2
          key: conan-cache-v1-${{ hashFiles('conanfile.py') }}
      - name: Restore ccache
        uses: actions/cache/restore@v4
        with:
          path: ~/.cache/ccache
          key: ccache-cache-v1-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ccache-cache-v1-${{ github.ref_name }}-
            ccache-cache-v1-
      - name: Install conan
        run: |
          sudo apt-get install -y ccache
          pip install conan
          conan profile detect --force
      - name: build OpenSees & OpenSeesPy
        run: |
          ccache -M 5G
          conan install . --build=missing
          cmake -S . -B build/Release -DCMAKE_TOOLCHAIN_FILE=build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/bin -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_Fortran_COMPILER_LAUNCHER=ccache
          cd build/Release
          cmake --build . --target OpenSees -j$(nproc)
          cmake --build . --target OpenSeesPy -j$(nproc)
          mv OpenSeesPy.so opensees.so
          ccache -s
      - name: Verification OpenSeesPy  # Simple Sanity Test
        run: |
          export PYTHONPATH="./build/Release"
          python3 -c "import sys; print(sys.path)"
          python3 ./EXAMPLES/ExamplePython/example_variable_analysis.py
      - name: Run pytest in tests/ folder
        run: |
          python3 -m pip install pytest scipy
          cp build/Release/opensees.so tests/
          cd tests
          pytest -v
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: OpenSees_Ubuntu
            path: |
              ./build/Release/OpenSees
              ./build/Release/opensees.so
      - name: Save conan cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ~/.conan2
          key: conan-cache-v1-${{ hashFiles('conanfile.py') }}
      - name: Save ccache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/ccache
          key: ccache-cache-v1-${{ github.ref_name }}-${{ github.sha }}
